/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.saojudas.sistema_academico.ui;

import java.awt.event.ActionEvent;
import java.util.Arrays;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import br.saojudas.sistema_academico.dao.CursoDAO;
import br.saojudas.sistema_academico.model.Curso;

/**
 *
 * @author Trabalho
 */
public class CursosTela extends javax.swing.JFrame {

	private static final String CONFIRMAR_CRIACAO = "Confirmar criação?";
	private static final String CANCELAR = "Cancelar";
	private static final String NOVO = "Novo";
	private static final String SALVAR_ALTERAÇÃO = "Salvar alteração?";
	private static final String ATUALIZAR = "Atualizar";
	private static final String CONFIRMAR_REMOCAO = "Confirma remoção?";
	private static final String REMOVER = "Remover";

	/**
	 * Creates new form CursosTela
	 */
	public CursosTela() {
		super("Cursos");
		initComponents();
		buscarCursos();
		setLocationRelativeTo(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		cursosComboBox = new javax.swing.JComboBox<>();
		idCursoTextField = new javax.swing.JTextField();
		nomeCursoTextField = new javax.swing.JTextField();
		tipoCursoTextField = new javax.swing.JTextField();
		novoButton = new javax.swing.JButton();
		atualizarButton = new javax.swing.JButton();
		removerButton = new javax.swing.JButton();
		cancelarButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Gerenciamento de cursos")));
		jPanel1.setPreferredSize(new java.awt.Dimension(322, 287));
		jPanel1.setRequestFocusEnabled(false);
		jPanel1.setVerifyInputWhenFocusTarget(false);

		cursosComboBox.setModel(new DefaultComboBoxModel<>());

		cursosComboBox.addActionListener(evt -> preencherActionPerformed(evt));
		removerButton.addActionListener(evt -> removerActionPerformed(evt));
		cancelarButton.addActionListener(evt -> cancelarActionPerformed(evt));
		atualizarButton.addActionListener(evt -> atualizarActionPerformed(evt));
		novoButton.addActionListener(evt -> novoActionPerformed(evt));

		idCursoTextField.setEditable(false);
		idCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("id"));
		idCursoTextField.setPreferredSize(new java.awt.Dimension(56, 20));

		nomeCursoTextField.setEditable(false);
		nomeCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("nome"));
		nomeCursoTextField.setPreferredSize(new java.awt.Dimension(56, 20));

		tipoCursoTextField.setEditable(false);
		tipoCursoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("tipo"));

		novoButton.setText(NOVO);

		atualizarButton.setText(ATUALIZAR);

		removerButton.setText(REMOVER);

		cancelarButton.setText(CANCELAR);

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(idCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(tipoCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING)
						.addComponent(nomeCursoTextField, javax.swing.GroupLayout.Alignment.TRAILING,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addComponent(cursosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45,
										Short.MAX_VALUE)
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(atualizarButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(cancelarButton, javax.swing.GroupLayout.Alignment.TRAILING,
												javax.swing.GroupLayout.PREFERRED_SIZE, 170,
												javax.swing.GroupLayout.PREFERRED_SIZE))))
						.addContainerGap()));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(19, 19, 19)
						.addComponent(cursosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(24, 24, 24)
						.addComponent(idCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(nomeCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(tipoCursoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(novoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(atualizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(cancelarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addContainerGap(15, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout
						.createSequentialGroup().addGap(39, 39, 39).addComponent(jPanel1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(44, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(26, Short.MAX_VALUE).addComponent(jPanel1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(25, 25, 25)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CursosTela.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CursosTela().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton atualizarButton;
	private javax.swing.JButton cancelarButton;
	private javax.swing.JButton novoButton;
	private javax.swing.JComboBox<Curso> cursosComboBox;
	private javax.swing.JTextField idCursoTextField;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField nomeCursoTextField;
	private javax.swing.JButton removerButton;
	private javax.swing.JTextField tipoCursoTextField;
	// End of variables declaration//GEN-END:variables

	private void buscarCursos() {
		try {
			CursoDAO cursoDAO = new CursoDAO();
			Curso[] cursos = cursoDAO.obterCursos();
			cursosComboBox.setModel(new DefaultComboBoxModel<>(cursos));
			preencherActionPerformed(null);
		} catch (Exception e) {
			JOptionPane.showMessageDialog(null, "Cursos indisponíveis, tente novamente mais tarde.");
			e.printStackTrace();
		}
	}

	private void preencherActionPerformed(ActionEvent evt) {
		Curso cursoSelecionado = (Curso) cursosComboBox.getSelectedItem();
		nomeCursoTextField.setText(cursoSelecionado.getNome());
		idCursoTextField.setText("" + cursoSelecionado.getId());
		tipoCursoTextField.setText(cursoSelecionado.getTipo());
		removerButton.setText(REMOVER);
		atualizarButton.setText(ATUALIZAR);
		nomeCursoTextField.setText(NOVO);
	}

	private void removerActionPerformed(ActionEvent evt) {
		if (removerButton.getText().equals(REMOVER)) {
			removerButton.setText(CONFIRMAR_REMOCAO);
		} else {
			Curso cursoSelecionado = (Curso) cursosComboBox.getSelectedItem();
			CursoDAO cursoDAO = new CursoDAO();
			try {
				cursoDAO.remover(cursoSelecionado.getId());
				buscarCursos();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, "Erro ao apagar");
				e.printStackTrace();
			}
			removerButton.setText(REMOVER);
		}
	}

	private void cancelarActionPerformed(ActionEvent evt) {
		buscarCursos();
		nomeCursoTextField.setEditable(false);
		tipoCursoTextField.setEditable(false);
	}

	private void atualizarActionPerformed(ActionEvent evt) {
		if (atualizarButton.getText().equals(ATUALIZAR)) {
			atualizarButton.setText(SALVAR_ALTERAÇÃO);
			idCursoTextField.setEditable(false);
			nomeCursoTextField.setEditable(true);
			tipoCursoTextField.setEditable(true);
		} else {
			Curso curso = new Curso(Integer.valueOf(idCursoTextField.getText()), nomeCursoTextField.getText(),
					tipoCursoTextField.getText());
			CursoDAO cursoDAO = new CursoDAO();
			try {
				cursoDAO.atualizar(curso);
				buscarCursos();
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, "Erro ao atualizar");
				e.printStackTrace();
			}
			atualizarButton.setText(ATUALIZAR);
		}
	}

	private void novoActionPerformed(ActionEvent evt) {
		if (novoButton.getText().equals(NOVO)) {
			novoButton.setText(CONFIRMAR_CRIACAO);
			CursoDAO cursoDAO = new CursoDAO();
			try {
				Curso[] cursos = cursoDAO.obterCursos();
				Curso[] novoCursos = Arrays.copyOf(cursos, cursos.length + 1);
				novoCursos[novoCursos.length - 1] = new Curso(0, "", "");
				cursosComboBox.setModel(new DefaultComboBoxModel<>(novoCursos));
				cursosComboBox.setSelectedIndex(novoCursos.length - 1);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, "Erro ao buscar cursos no banco");
				e.printStackTrace();
			}
			nomeCursoTextField.setEditable(true);
			tipoCursoTextField.setEditable(true);
		} else {
			Curso curso = new Curso(0, nomeCursoTextField.getText(), tipoCursoTextField.getText());
			CursoDAO cursoDAO = new CursoDAO();
			try {
				cursoDAO.criar(curso);
			} catch (Exception e) {
				JOptionPane.showMessageDialog(null, "Erro ao criar curso no banco");
				e.printStackTrace();
			}
			buscarCursos();
			novoButton.setText(NOVO);
			nomeCursoTextField.setEditable(false);
			tipoCursoTextField.setEditable(false);
		}
	}

}
